export const PREDICTION_WEIGHTS = {
  GOAL_PROBABILITY: {
    OVERALL_PROGRESS: 0.25,
    GOAL_HEALTH: 0.20,
    TIMELINE_HEALTH: 0.15,
    WEEKLY_CONSISTENCY: 0.15,
    MISSION_COMPLETION: 0.15,
    ACTIVE_STREAK_BONUS: 0.10 // Max 10% bonus
  },
  PLACEMENT_READINESS: {
    READINESS_SCORE: 0.35,
    GOAL_ALIGNMENT: 0.25,
    MISSION_COMPLETION: 0.20,
    RECOMMENDATION_COMPLETION: 0.20
  },
  VELOCITY: {
    MISSION_VELOCITY: 0.50,
    RECOMMENDATION_VELOCITY: 0.30,
    WEEKLY_CONSISTENCY: 0.20
  }
};

export const PREDICTION_VERSION = {
  version: 1,
  formulaVersion: "v1.0"
};
